### ISSUE TITLE
PyPI

### ISSUE THREAD

**Issue by jayvdb** [adsr303/awking#1]
Are you planning a PyPI release soon?

These seems similar in intention as pywikibot's text manipulation core, `replaceExcept`, which works the opposite way by defining exceptions for parts of the document which shouldnt touched by any replacements.

https://github.com/wikimedia/pywikibot/blob/master/pywikibot/textlib.py#L355 for the function

https://github.com/wikimedia/pywikibot/blob/master/pywikibot/textlib.py#L258 for some of the exception definitions.

**Comment by adsr303** [comment]
Sorry about replying this late. Anyway, I'd thought I'd release it sooner but it needs better documentation. And code review.

**Comment by jayvdb** [comment]
Maybe we should try to replace the pywikibot function with this package, as pywikibot has a very large test suite which will implicitly test this codebase.

**Comment by adsr303** [comment]
Please note that `RangeGrouper` produces only groups of those items from the iterable that fall within the ranges. Anything else from the input is omitted. Assuming these lines of input:

```
text 1
text 2
group start 1
text 3
group end 1
text 4
group start 2
text 5
group end 2
text 6
```

a `RangeGrouper('start', 'end', lines)` would produce these groups:

```
['group start 1', 'text 3', 'group end 1'], ['group start 2', 'text 5', 'group end 2']
```

Actually, if I understand your code correctly, maybe you could produce groups of replacement indices. Am I making sense?

**Comment by adsr303** [comment]
Officially released: https://pypi.org/project/awking/

Happy awking!
